coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
       # advanced
        branches:
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
