name: E2E Install from git
# TODO test global installs, too?
on:
  # nightly
  schedule:
    - cron:  '0 0 * * *'
  # To temporarily enable on your branch for verification
  # push: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  npm:
    name: "npm"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
    steps:
      # install node
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Test
        run: |
          npm --version
          echo '{"scripts": {"test": "ts-node -vvv"}}' > package.json
          npm install https://github.com/TypeStrong/ts-node#${{ github.ref_name }}
          npm test
  pnpm:
    name: "pnpm"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
    steps:
      # install node
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Test
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm --version
          echo '{"scripts": {"test": "ts-node -vvv"}}' > package.json
          pnpm install https://github.com/TypeStrong/ts-node#${{ github.ref_name }}
          pnpm test
  yarn:
    name: "yarn"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
    steps:
      # install node
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Test
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn --version
          echo '{"scripts": {"test": "ts-node -vvv"}}' > package.json
          yarn add ts-node@https://github.com/TypeStrong/ts-node#${{ github.ref_name }}
          yarn add typescript
          yarn test
  yarn1:
    name: "yarn1 (officially *not* supported)"
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
    steps:
      # install node
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Test
        run: |
          npm install -g yarn
          yarn --version
          yarn cache list
          echo '{"scripts": {"test": "ts-node -vvv"}}' > package.json
          yarn add https://github.com/TypeStrong/ts-node#${{ github.ref_name }}
          yarn test
